release-matrix: &release-matrix
  goos: [linux, darwin, windows]
  goarch: [amd64, arm64]

name: Create Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true

permissions:
  contents: write

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Tag
        id: create_tag
        run: |
          TAG_NAME="${{ github.event.inputs.tag_name }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

  build:
    needs: create_tag
    name: Create Release
    runs-on: ubuntu-24.0ยง
    strategy:
      matrix: *release-matrix

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Build
        run: make build GOOS=${{ matrix.goarch }} GOARCH=${{ matrix.goarch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: shakespeare-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/shakespeare

    
  release:
    needs: build
    runs-on: ubuntu-24.04
    
    strategy:
      matrix: *release-matrix

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: shakespeare-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/shakespeare-${{ matrix.goos }}-${{ matrix.goarch }}


      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.tag_name }}
          files: |
            dist/shakespeare-${{ matrix.goos }}-${{ matrix.goarch }}
        