name: Create Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true

permissions:
  contents: write

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Create Tag
        id: create_tag
        run: |
          TAG_NAME="${{ github.event.inputs.tag_name }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

  release:
    needs: create_tag
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      
      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.23.4'
      
      - name: Install dependencies
        run: go mod download

      - name: Build
        run: make build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.tag_name }}
        