name: Create Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true

permissions:
  contents: write

jobs:
  create_tag:
    name: Create Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Tag
        id: create_tag
        run: |
          TAG_NAME="${{ github.event.inputs.tag_name }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

  build:
    needs: create_tag
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Build
        run: |
            for GOOS in linux darwin windows; do
            for GOARCH in amd64 arm64; do
              make build GOOS=$GOOS GOARCH=$GOARCH
              mv dist/shakespeare dist/shakespeare-$GOOS-$GOARCH
            done
            done


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: shakespeare-binaries
          path: dist/

    
  release:
    needs: build
    name: Release
    runs-on: ubuntu-24.04

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: shakespeare-binaries
          path: dist/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.tag_name }}
          files: |
            dist/*
        