name: Unit Test
run-name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Go
      uses: actions/setup-go@v5.3.0
      with:
        go-version: '1.23.4'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: make test